### ISSUE TITLE
连接到Go-cqhttp服务端失败

### ISSUE THREAD

**Issue by liulyxandy-codemao** [lc-cn/onebot-client#3]
代码片段：
```js
let client = new Client(10001, {
    remote_url: “ws://127.0.0.1:8080”,
    access_token: "example"
})


logger.notice('正在登录...');

client.start().then(()=>{
    logger.notice('协议启动成功')
    onlineAction(client) 
})
.catch((e)=>{
    console.log(e)
    console.log("Error")
})
```
输出片段：
```
LYXBOT NOTICE 正在登录...
undefined
Error
```
gocq配置：
```yaml
# go-cqhttp 默认配置文件

account: # 账号相关
  uin: 10001 # QQ账号
  password: 'example' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制
    ......

......

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: 'example'
  ......

......

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      address: 0.0.0.0:8080
      middlewares:
        <<: *default # 引用默认中间件
```
gocq日志：
```
[2023-08-07 10:19:30] [INFO]: CQ WebSocket 服务器已启动: [::]:8080
......
[2023-08-07 10:19:30] [INFO]: 开始诊断网络情况
[2023-08-07 10:19:32] [INFO]: 网络诊断完成. 未发现问题
[2023-08-07 10:19:42] [INFO]: 接受 WebSocket 连接: 127.0.0.1:56179 (/)
```
